### ISSUE TITLE
Support Metering Batch API on Client

### ISSUE THREAD

**Issue by code4clouds** [Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK#34]
**Is your feature request related to a problem? Please describe.**
The API Batch implementation is missing.

**Describe the solution you'd like**
Implement the missing API

**Describe alternatives you've considered**
Workaround is to send metering data every hour, instead of once a day.

**Additional context**

**Comment by dev-kiranbanda** [comment]
The metering API client in the client library has the following implementation:

```csharp

/// <summary>
/// Emits the batch usage event asynchronous.
/// </summary>
/// <param name="batchUsageEventRequest">The batch usage event request.</param>
/// <returns> Batch Usage.</returns>
Task<MeteringBatchUsageResult> EmitBatchUsageEventAsync(IEnumerable<MeteringUsageRequest> batchUsageEventRequest);

```

**Comment by code4clouds** [comment]
@ankisho Feature is now implemented.
