### ISSUE TITLE
Azure Deployment not running from this repo.

### ISSUE THREAD

**Issue by code4clouds** [Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK#39]
**Describe the bug**
The Azure ARM deployment button deploys the scripts from a different location other than this repo.

**To Reproduce**
1. Click the deploy to Azure and check the URL for the .json file (https://raw.githubusercontent.com/SpektraSystems/AMP-SDK-Sample/master/deploy/arm-deploy-v1.json)

**Expected behavior**
The expected behavior is the ARM template deployment runs from this location.

**Comment by dev-kiranbanda** [comment]
Got rid of all the external references in the ARM templates / powershell scripts. ARM template expects the path to the web application packages and the location where the bacpac file is stored.
