### ISSUE TITLE
Provide customer information on how to create the admin user.

### ISSUE THREAD

**Issue by code4clouds** [Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK#41]
**Is your feature request related to a problem? Please describe.**
There is no documentation on how to create the first admin user.

**Describe the solution you'd like**
Provide information that the admin email is supposed to be a the friendly user table and provide screenshots.

**Describe alternatives you've considered**
Alternatively the ARM deployment script creation should prompt for the admin email in the Portal textfield and push it to the deployed DB.

**Comment by dev-kiranbanda** [comment]
I went by your inputs and accomodated this as an input parameter to the ARM template. The template would add the admin users to the application configuration. The admin portal consumes this detail and initializes the admin users at the time of startup.
