### ISSUE TITLE
Provide guidance to user on where to find the DB Creds.

### ISSUE THREAD

**Issue by code4clouds** [Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK#42]
**Is your feature request related to a problem? Please describe.**
There is no clear documentation on where customer will find the SQL DB creds needed for the config.json files.

**Describe the solution you'd like**
Provide information and screenshots of the location where the user will find the DB creds needed for the config.json files.

**Describe alternatives you've considered**
The ARM template deploys the db and outputs the creds for the customer to copy and paste.

**Comment by dev-kiranbanda** [comment]
@code4clouds - PR #82 has the ARM template and Powershell script that can be used to deploy the resources [ web apps and SQL Azure database ] to Azure. The ARM template outputs the URLs to the web apps and the connection string to the database.

**Comment by code4clouds** [comment]
I also noted there is an insert script in 2.0 that shows the customer where he needs to add the email. 👍🏼
