### ISSUE TITLE
WebApp support of environmental variables.

### ISSUE THREAD

**Issue by code4clouds** [Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK#83]
**Is your feature request related to a problem? Please describe.**
Customer wants to use WebApps environmental variable, so they can pass their KeyVault values,

**Describe the solution you'd like**
I would like the WebApp to take the environmental variables from the WebApp Settings and if there are none setup then use the config.json file as usual.

**Comment by dev-kiranbanda** [comment]
Hi Julio,

I did anticipate this question and had got it covered in my documentation earlier that got changed for the Build.

Please kindly check this link - https://github.com/Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK/blob/2.1_development/docs/Installation-Instructions.md#set-up-the-sample-client-application-locally

Here is the content that I think would address the question:

**Note:** When defining the keys in Azure App Service -> Configuration -> App Settings, refer to the below example for correctness:

Name | Value
-- | --
SaaSApiConfiguration__GrantType | client_credentials

>Tip __(double underscore) should be used to define the config items that appear as nested keys in appSettings.json
