### ISSUE TITLE
New subscription stuck in PendingActivation

### ISSUE THREAD

**Issue by lostmsu** [Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK#97]
**Describe the bug**
I just deployed the ARM template from the demo, and created a **preview** offer (e.g. it has not yet been published), that is only visible to my own account.

![image](https://user-images.githubusercontent.com/239520/87723315-7ca8f900-c76e-11ea-92a8-11a066291a56.png)

The issue is subscription does not get activated.

**To Reproduce**
When I try to subscribe, and get the "Activate your new subscription" email, "Activate Now" button brings me to `lic-portal` site, where I accept the terms etc. In the end I get access to the portal where my plan is listed under `Subscriptions`. However, its status is `PendingActivation` with no clear reason as to why it is not yet `Subscribed`.

I've even added (https://github.com/losttech/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK/commit/b60df581a30afd512c2e3c10add98ae111ed376e) an admin portal view to check out the contents of `WebJobSubscriptionStatus`, and it appears to be empty.

![image](https://user-images.githubusercontent.com/239520/87723627-e923f800-c76e-11ea-97d5-81c05ea70d07.png)

**Expected behavior**
The status should be `Subscribed` or `ActivationFailed`

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chromium-based Edge

**Additional context**

**Comment by lostmsu** [comment]
Oh, I figured out I have to manually activate the subscription from the admin portal. Is there a way to make it happen automatically? [This PR](https://github.com/Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK/pull/46) seems to be related, but I can't find documentation for it.

**Comment by santhoshbomma9** [comment]
@lostmsu 
Please check the app config values("IsAutomaticProvisioningSupported") to change the activation flow from landing page. 
https://github.com/Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK/tree/master/deployment/Database#application-configuration

**Comment by lostmsu** [comment]
Thanks. Added https://github.com/losttech/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK/commit/46733a5949d8a95e5cb17c3ef78dd82311563fd6 and https://github.com/losttech/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK/commit/e0c11dcc63a264c0d9e1def08ddc1ab0a4ddd81b to my fork.
